/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'skuli' at '10/20/14 5:24 PM' with Gradle 2.1
 *
 * @author skuli, @date 10/20/14 5:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
